### ISSUE TITLE
Set Defaults button

### ISSUE THREAD

**Issue by River-b** [builder555/pinecil-v2#3]
Is there a way to have a button that will "Reset All to Defaults"  which will restore everything to exactly the way  it is released with the  firmware version the person is on.  

Background: Ralim  sends out all firmware with a specific set of defaults that he thinks more people will use.  
sometimes people change so many settings and don't know what they messed up , they just want an easy way to restore it all quickly  and get all default sleep, hall sensor, temperature default settings.  We have this ability inside Advanced menu now  in the Reset Defaults but not in BLE.

**Comment by builder555** [comment]
I'll check if it's available through BLE interface.

**Comment by builder555** [comment]
@River-b doesn't look like it's exposed, at least I can't find it. You can create an issue with [IronOS](/Ralim/IronOS).

**Comment by River-b** [comment]
> @River-b doesn't look like it's exposed, at least I can't find it. You can create an issue with [IronOS](/Ralim/IronOS).

https://github.com/Ralim/IronOS/issues/1566

**Comment by builder555** [comment]
branch [v2.21](../tree/v2.21) works with [this](https://github.com/Ralim/IronOS/suites/10919790100/artifacts/551993774) artifact. I'll wait before merging in case @Ralim makes other changes. It's also backwards compatible
