### ISSUE TITLE
BLE entry in Wiki page

### ISSUE THREAD

**Issue by River-b** [builder555/pinecil-v2#9]
I'm adding an entry for this BLE app to the Pinecil Wiki. 
I put Robert, don't know if you have anything else you want me to add to this.
https://wiki.pine64.org/wiki/Pinecil#Development_Projects

For quick questions, do you happen to have discord, telegram, matrix?  and are you already in the Pine64 community chat for discord/telegram/matrix?  sometimes it might be easier to ping you in there for short questions about the app (if you are could you tell me your name in there thanks). 
If you are doing development,  the Pinecil-Dev channel is for  developers. Ralimtek hangs out in there and uses Telegram to bridge into the Pine64 Discord server chat so you might find that convenient.

The regular "pinecil" channel is for troubleshooting hardware and advice needed for  how to update firmware, general new user questions.

**Comment by builder555** [comment]
I'm not on discord or matrix, although I can sign up. What's the link to Pine64 discord?
